[package]
name = "oscar-tools"
version = "0.1.0"
authors = ["Pedro J. Ortiz <pedro@pjortiz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
log = "0.4.14"
env_logger = "0.9.0"
serde_json = "1.0.78"
rayon = "1.5.1"
flate2 = "1.0.22"

[dev-dependencies]
tempfile = "3.3.0"
